begin;
create table ns.store_aisles(tenant_id uuid not null references ns.tenants,id uuid not null default gen_random_uuid(),number integer not null check(number between 1 and 8),label text not null,sides text[] not null default '{}',categories text[] not null default '{}',x integer check(x between 0 and 100),y integer check(y between 0 and 100),active boolean not null default true,version integer not null default 1,primary key(tenant_id,id),unique(tenant_id,number));
insert into ns.store_aisles(tenant_id,number,label) select '11111111-1111-4111-8111-111111111111',n,'Aisle '||n from generate_series(1,8) n;
create table ns.store_nodes(tenant_id uuid not null references ns.tenants,id uuid not null default gen_random_uuid(),label text not null,kind text not null check(kind in ('entrance','service_counter','path')),x integer not null check(x between 0 and 100),y integer not null check(y between 0 and 100),active boolean not null default true,version integer not null default 1,primary key(tenant_id,id));
create table ns.store_edges(tenant_id uuid not null,id uuid not null default gen_random_uuid(),from_node uuid not null,to_node uuid not null,active boolean not null default true,primary key(tenant_id,id),unique(tenant_id,from_node,to_node),check(from_node<>to_node),foreign key(tenant_id,from_node) references ns.store_nodes(tenant_id,id),foreign key(tenant_id,to_node) references ns.store_nodes(tenant_id,id));
create table ns.store_locations(tenant_id uuid not null references ns.tenants,id uuid not null default gen_random_uuid(),pool text not null check(pool in ('retail','breaker','excess')),label text not null,aisle_id uuid,side text,zone text not null default '',categories text[] not null default '{}',approved_retail boolean not null default false,active boolean not null default true,version integer not null default 1,primary key(tenant_id,id),check(not approved_retail or pool='retail'),check(pool='retail' or aisle_id is null),foreign key(tenant_id,aisle_id) references ns.store_aisles(tenant_id,id));
create table ns.store_products(tenant_id uuid not null references ns.tenants,id uuid not null default gen_random_uuid(),shopify_product_id text not null,title text not null,family text not null,handle text not null,fixture boolean not null default false,version integer not null default 1,primary key(tenant_id,id),unique(tenant_id,shopify_product_id),unique(tenant_id,handle));
create table ns.store_variants(tenant_id uuid not null,id uuid not null default gen_random_uuid(),product_id uuid not null,shopify_variant_id text not null,sku text not null,barcode text,verified boolean not null default false,evidence text not null,version integer not null default 1,primary key(tenant_id,id),unique(tenant_id,id,product_id),unique(tenant_id,shopify_variant_id),unique(tenant_id,sku),unique(tenant_id,barcode),foreign key(tenant_id,product_id) references ns.store_products(tenant_id,id));
create table ns.store_assignments(tenant_id uuid not null,id uuid not null default gen_random_uuid(),variant_id uuid not null,location_id uuid not null,version integer not null default 1,primary key(tenant_id,id),unique(tenant_id,variant_id,location_id),foreign key(tenant_id,variant_id) references ns.store_variants(tenant_id,id),foreign key(tenant_id,location_id) references ns.store_locations(tenant_id,id));
create table ns.store_qr(tenant_id uuid not null,id uuid not null default gen_random_uuid(),token text not null check(token~'^[A-Za-z0-9_-]{24}$'),product_id uuid not null,variant_id uuid,placement_id uuid,campaign_key text,destination text not null check(destination in ('product','retail_locator')),active boolean not null default true,version integer not null default 1,primary key(tenant_id,id),unique(token),foreign key(tenant_id,product_id) references ns.store_products(tenant_id,id),foreign key(tenant_id,variant_id,product_id) references ns.store_variants(tenant_id,id,product_id),foreign key(tenant_id,placement_id) references ns.store_locations(tenant_id,id));
create table ns.store_audit(tenant_id uuid not null,id uuid not null default gen_random_uuid(),actor_id uuid not null,object_id uuid not null,action text not null,reason text not null,before_value jsonb,after_value jsonb,created_at timestamptz not null default now(),primary key(tenant_id,id),foreign key(tenant_id,actor_id) references ns.staff_memberships(tenant_id,id));
create table ns.store_pickups(tenant_id uuid not null,id uuid not null default gen_random_uuid(),customer_id uuid not null,order_id text not null,state text not null check(state in ('paid','preparing','ready','collected','canceled')),fixture boolean not null default true check(fixture),version integer not null default 1,primary key(tenant_id,id),unique(tenant_id,order_id),foreign key(tenant_id,customer_id) references ns.customers(tenant_id,id));
create function ns.freeze_store_identity() returns trigger language plpgsql as $$ begin
 if tg_table_name='store_qr' then if (new.tenant_id,new.id,new.token) is distinct from (old.tenant_id,old.id,old.token) then raise exception 'Printed QR identity is immutable'; end if;
 elsif tg_table_name='store_locations' then if (new.tenant_id,new.id,new.pool) is distinct from (old.tenant_id,old.id,old.pool) then raise exception 'Inventory pool identity is immutable'; end if;
 elsif tg_table_name='store_products' then if (new.tenant_id,new.id,new.shopify_product_id,new.fixture) is distinct from (old.tenant_id,old.id,old.shopify_product_id,old.fixture) then raise exception 'Product identity is immutable'; end if;
 elsif tg_table_name='store_variants' then if (new.tenant_id,new.id,new.product_id,new.shopify_variant_id) is distinct from (old.tenant_id,old.id,old.product_id,old.shopify_variant_id) then raise exception 'Variant identity is immutable'; end if;
 elsif tg_table_name='store_assignments' then if (new.tenant_id,new.id,new.variant_id) is distinct from (old.tenant_id,old.id,old.variant_id) then raise exception 'Assigned product identity is immutable'; end if;
 elsif tg_table_name='store_pickups' then if (new.tenant_id,new.id,new.customer_id,new.order_id,new.fixture) is distinct from (old.tenant_id,old.id,old.customer_id,old.order_id,old.fixture) then raise exception 'Pickup identity is immutable'; end if;
 end if;return new;end $$;
do $$ declare t text;begin
 foreach t in array array['store_aisles','store_nodes','store_edges','store_locations','store_products','store_variants','store_assignments','store_qr','store_audit','store_pickups'] loop
 execute format('alter table ns.%I enable row level security',t);
 execute format('grant select,insert,update on ns.%I to northside_runtime',t);
 execute format('create policy store_read on ns.%I for select to northside_runtime using(ns.staff_can(tenant_id,array[''owner'',''admin'',''operations'',''read_only'']))',t);
 execute format('create policy store_write on ns.%I to northside_runtime using(ns.staff_can(tenant_id,array[''owner'',''admin'',''operations''])) with check(ns.staff_can(tenant_id,array[''owner'',''admin'',''operations'']))',t);
 end loop;
 foreach t in array array['store_qr','store_products','store_variants','store_assignments','store_pickups','store_locations'] loop
 execute format('create trigger store_identity before update on ns.%I for each row execute function ns.freeze_store_identity()',t);
 end loop;
end $$;
create trigger store_append_only before update or delete on ns.store_audit for each row execute function ns.prevent_rewrite();
-- Only this constrained projection crosses the staff/customer inventory-location boundary.
create function ns.store_retail_product(p uuid,sample boolean) returns jsonb language sql stable security definer set search_path=pg_catalog,ns as $$
 select jsonb_build_object('id',s.id,'product_id',s.shopify_product_id,'title',s.title,'handle',s.handle,'fixture',s.fixture,'variants',coalesce((select jsonb_agg(jsonb_build_object('id',v.id,'variant_id',v.shopify_variant_id,'sku',v.sku,'locations',coalesce((select jsonb_agg(jsonb_build_object('label',l.label,'zone',l.zone,'side',l.side,'aisle',a.label)) from ns.store_assignments x join ns.store_locations l on l.tenant_id=x.tenant_id and l.id=x.location_id left join ns.store_aisles a on a.tenant_id=l.tenant_id and a.id=l.aisle_id where x.tenant_id=v.tenant_id and x.variant_id=v.id and l.pool='retail' and l.approved_retail and l.active and (a.id is null or a.active)),'[]'::jsonb))) from ns.store_variants v where v.tenant_id=s.tenant_id and v.product_id=s.id and v.verified),'[]'::jsonb)) from ns.store_products s where s.tenant_id='11111111-1111-4111-8111-111111111111' and s.id=p and s.fixture=sample
$$;
-- The resolver returns only opaque product/variant identities, never QR placement or private pool positions.
create function ns.store_public_target(k text,v text,sample boolean) returns table(product_id uuid,variant_id uuid,campaign_key text,destination text) language sql stable security definer set search_path=pg_catalog,ns as $$
 select q.product_id,q.variant_id,q.campaign_key,q.destination from ns.store_qr q join ns.store_products p on p.tenant_id=q.tenant_id and p.id=q.product_id where k='qr' and q.token=v and q.active and p.fixture=sample and q.tenant_id='11111111-1111-4111-8111-111111111111'
 union all select b.product_id,b.id,null,'product' from ns.store_variants b join ns.store_products p on p.tenant_id=b.tenant_id and p.id=b.product_id where k='barcode' and b.barcode=v and b.verified and p.fixture=sample and b.tenant_id='11111111-1111-4111-8111-111111111111'
 union all select p.id,null,null,'product' from ns.store_products p where k='handle' and p.handle=v and p.fixture=sample and p.tenant_id='11111111-1111-4111-8111-111111111111'
$$;
revoke all on function ns.store_retail_product(uuid,boolean),ns.store_public_target(text,text,boolean) from public;
grant execute on function ns.store_retail_product(uuid,boolean),ns.store_public_target(text,text,boolean) to northside_runtime;
commit;
